[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake"]

[phases.install]
cmds = ["npm ci --include=optional"]

[phases.build]
cmds = ["npm run build --if-present"]

[start]
cmd = "npm start"
